### PR TITLE
Fix ended lives order

### LINKED ISSUE #25: [BUG] Ended lives with incorrect order
**Describe the bug**
Current procedures of pushing missing current lives to ended lives may cause incontinent order.

**Expected behavior**
Ended lives show in the order of start_at time.

**Screenshots**

### PR DESCRIPTION
**Pull request by YunzheZJU**
This pr expects to fix #25.

#### Propsed changes
  - Respect the order of start_at when moving kives from current to ended.
  - Reduce unnecessary updates of scrollTop when ended lives are updated.

### CODE REVIEW

File: src/background/workflows/index.js [hunk 1]
```diff
@@ -74,17 +74,20 @@ const syncCurrentLives = async () => {
   console.log(`[syncLives]Badge text has been set to ${lives.length}`)
 
   // Subscription is simplified cause here is the only mutation of currentLives
+  const endedLives = [...(getCachedEndedLives() ?? [])]
```
Comment (YunzheZJU) [inline src/background/workflows/index.js:77]:
```suggestion
  const endedLives = getCachedEndedLives() ?? []
```
